'use strict';
// Training records are independent of nutrition check-ins and legacy weekday IDs.
let coachDate=null;
const muscleMap={chest:[['Chest'],['Shoulders','Triceps']],row:[['Back'],['Biceps']],shoulder:[['Shoulders'],['Triceps']],pull:[['Back'],['Biceps']],raise:[['Shoulders'],[]],rear:[['Shoulders','Back'],[]],biceps:[['Biceps'],[]],triceps:[['Triceps'],[]],core:[['Core'],[]],squat:[['Quads','Glutes'],[]],hinge:[['Hamstrings','Glutes'],['Back']],lunge:[['Quads','Glutes'],[]],curl:[['Hamstrings'],[]],calf:[['Calves'],[]],press:[['Quads','Glutes'],[]],glute:[['Glutes'],['Hamstrings']],step:[['Quads','Glutes'],[]]};
function cleanTraining(input){
 const out={};if(input==null)return out;if(typeof input!=='object'||Array.isArray(input))throw Error('Invalid training');
 for(const [date,s] of Object.entries(input)){
  if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||localDate(new Date(date+'T12:00:00'))!==date||!s||!Number.isInteger(s.plan)||s.plan<0||s.plan>6)throw Error('Invalid session');
  const row={plan:s.plan,finished:!!s.finished,sets:{},recovery:{}};
  for(const k of ['energy','upper','lower','core']){const v=s.recovery?.[k]??0;if(!Number.isInteger(v)||v<0||v>2)throw Error('Invalid recovery');row.recovery[k]=v}row.recovery.pain=!!s.recovery?.pain;
  row.minutes=s.minutes??null;if(row.minutes!=null&&(!Number.isFinite(row.minutes)||row.minutes<0||row.minutes>300))throw Error('Invalid minutes');
  if(s.sets!=null&&(typeof s.sets!=='object'||Array.isArray(s.sets)))throw Error('Invalid sets');
  // Valid IDs differ by session; this also prevents collisions between A/B variants.
  const ids={0:['chest','row','shoulder','pull','raise','core'],1:['squat','hinge','lunge','curl','calf','core'],2:[],3:['chest','row','pull','rear','biceps','triceps','core'],4:['press','glute','step','curl','calf','core'],5:[],6:[]}[s.plan];
  for(const [id,sets] of Object.entries(s.sets||{})){
   if(!ids.includes(id)||!Array.isArray(sets)||sets.length>8)throw Error('Invalid exercise');
   row.sets[id]=sets.map(v=>{if(!v||typeof v!=='object')throw Error('Invalid set');const r={};for(const [k,max] of [['weight',1500],['reps',600],['rir',10]]){r[k]=v[k]??null;if(r[k]!=null&&(!Number.isFinite(r[k])||r[k]<0||r[k]>max||(k!=='weight'&&!Number.isInteger(r[k]))))throw Error('Invalid set value')}r.done=!!v.done;if(r.done&&!(r.reps>0))throw Error('Completed set needs reps');return r});
  }out[date]=row;
 }return out;
}
function sessionsBefore(date,inclusive=false){return Object.entries(state.training||{}).filter(([dt])=>inclusive?dt<=date:dt<date).sort(([a],[b])=>a.localeCompare(b))}
function actualSets(s){return Object.values(s.sets||{}).flat().filter(v=>v.done)}
function workedMuscles(s,includeSupport=false){return [...new Set(Object.entries(s.sets||{}).filter(([,v])=>v.some(x=>x.done)).flatMap(([id])=>includeSupport?muscleMap[id].flat():muscleMap[id][0]))]}
function gap(a,b){return Math.round((Date.parse(a+'T12:00:00Z')-Date.parse(b+'T12:00:00Z'))/86400000)}
function nextSlot(date){const prior=sessionsBefore(date).filter(([,s])=>s.finished);return prior.length?(prior.at(-1)[1].plan+1)%7:0}
function recommendation(date){
 const saved=state.training?.[date],plan=saved?.plan??nextSlot(date),prior=sessionsBefore(date),r=saved?.recovery||{},recent=prior.filter(([dt])=>gap(date,dt)<2),muscles=new Set(recent.flatMap(([,s])=>workedMuscles(s,true))),kind=trainingPlan[plan].kind;
 const legacy=Object.entries(state.days).filter(([dt,d])=>dt<date&&gap(date,dt)<2&&d.workout&&!state.training?.[dt]);
 const weekly=new Set([...prior.filter(([dt,s])=>gap(date,dt)<7&&actualSets(s).length).map(([dt])=>dt),...Object.entries(state.days).filter(([dt,d])=>dt<date&&gap(date,dt)<7&&d.workout).map(([dt])=>dt)]);
 const region=[0,3].includes(plan)?'upper':'lower';let reason='',blocked=false;
 if(r.pain){blocked=true;reason='You reported pain. Pause training; do not push through painful movements.'}
 else if(r.energy===2){blocked=true;reason='You reported very low energy. Take a recovery day; this session will wait.'}
 else if(kind==='strength'){
  const main=trainingPlan[plan].exercises.filter(e=>e[0]!=='core').flatMap(e=>muscleMap[e[0]][0]);
  if(legacy.length){blocked=true;reason='Yesterday’s older workout has no reliable muscle details. Take a recovery day before the next lift.'}
  else if(main.some(m=>muscles.has(m))){blocked=true;reason='This session overlaps muscles trained yesterday. Give them a day between strength sessions.'}
  else if(r[region]===2){blocked=true;reason='Your reported soreness is high in this session’s muscles. Let them recover; the workout stays queued.'}
  else if(weekly.size>=Math.min(4,state.settings.lifts)){blocked=true;reason='Your rolling seven-day strength target is met. Recover today; no catch-up workouts are added.'}
  else if([1,2].every(n=>weekly.has(shiftDate(date,-n)))){blocked=true;reason='You lifted on both previous days. Take a break before your next strength session.'}
 }
 const skipCore=muscles.has('Core')||r.core===2;
 if(!reason)reason=kind==='strength'?'Next in your sequence, based on completed sessions. Missed days never reset it.':kind==='run'?'An easy aerobic day between strength blocks. A walk counts here.':'A planned recovery day before the sequence starts again.';
 return {plan,blocked,reason,skipCore,light:r.energy===1||r[region]===1,walk:recent.some(([,s])=>workedMuscles(s).some(m=>['Quads','Glutes','Hamstrings','Calves'].includes(m)))||r.lower>=1};
}
function setTarget(plan,id,date){const spec=trainingPlan[plan].exercises.find(e=>e[0]===id),m=spec[2].match(/(\d+) × (\d+)(?:–(\d+))?/),r=recommendation(date),count=sessionsBefore(date).filter(([,s])=>s.finished&&trainingPlan[s.plan].kind==='strength').length;return {sets:(state.settings.experience!=='regular'&&count<8)||r.light?Math.min(2,+m[1]):+m[1],low:+m[2],high:+(m[3]||m[2]),timed:spec[2].includes('sec'),side:spec[2].includes('side')};}
function priorExercise(plan,id,date){return sessionsBefore(date).reverse().filter(([,s])=>demoMap[s.plan]?.[id]?.[0]===demoMap[plan]?.[id]?.[0]&&s.sets?.[id]?.some(v=>v.done)).map(([dt,s])=>({date:dt,sets:s.sets[id].filter(v=>v.done)}))}
function loadAdvice(plan,id,date){
 const t=setTarget(plan,id,date),past=priorExercise(plan,id,date),last=past[0];if(!last)return 'First log: choose a comfortable load, leaving 2–3 good reps in reserve. No starting weight is guessed.';
 if(gap(date,last.date)>14)return 'Returning after a break: use lighter practice sets and reassess your working load. No increase suggested.';
 if(recommendation(date).light||recommendation(date).blocked)return 'Recovery comes first: use an easier load when ready. No increase suggested today.';
 if(last.sets.some(v=>v.reps<t.low||v.rir===0))return 'Last time included missed target reps or no reps in reserve. Reduce the load by a small step if needed to keep 2–3 good reps available.';
 if(t.timed)return 'Build hold time within the target range while keeping position steady. Stop before form changes.';
 const ready=past.slice(0,2);if(ready.length===2&&ready.every(p=>p.sets.length>=t.sets&&p.sets.every(v=>v.reps>=t.high&&v.rir>=2&&v.weight>0))&&new Set(ready.flatMap(p=>p.sets.map(v=>v.weight))).size===1)return 'Two successful logs at the same load: try the smallest available increase (no more than 5%), then return to the lower rep target. Keep the load if that jump feels too large.';
 return 'Keep your working load and build toward the top of the rep range. An increase needs two qualifying logs with effort recorded.';
}
function muscleHistory(date){const rows=sessionsBefore(date,true).filter(([dt])=>gap(date,dt)<7),totals={};for(const [,s] of rows)for(const [id,sets] of Object.entries(s.sets)){const n=sets.filter(v=>v.done).length;if(!n)continue;muscleMap[id].forEach((list,index)=>list.forEach(m=>{totals[m]||=[0,0];totals[m][index]+=n}))}return `<section class="card"><div class="eyebrow">Last seven days · saved sets only</div><h2>Your muscle balance</h2>${Object.entries(totals).map(([m,[direct,assist]])=>`<div class="row muscle-row"><b>${m}</b><span>${direct} direct · ${assist} supporting sets</span></div>`).join('')||'<p class="muted">Complete and save a set to start your muscle history.</p>'}<p class="fine">Muscle involvement is an estimate. Compound sets can appear for several muscles; do not add these rows together. Supporting work is shown separately. This is not a measurement of biological recovery.</p></section>`}
function coachCard(){const r=recommendation(localDate()),s=state.training?.[localDate()];return `<section class="card training-teaser"><div class="eyebrow">Adapts to your actual training</div><h2>${s?.finished?'Session saved ✓':r.blocked?'Recovery today':trainingPlan[r.plan].name}</h2><p>${s?.finished?'Next up: '+trainingPlan[(s.plan+1)%7].name+'. Your recovery check will determine when to do it.':r.reason}</p><button class="secondary wide" data-go="train">Open your coach →</button></section>`}
function adaptiveTrainView(){
 const date=coachDate||localDate(),r=recommendation(date),p=trainingPlan[r.plan],s=state.training?.[date]||{sets:{},recovery:{}},rec=s.recovery||{};
 return title('Training that moves with you','Your next good session.','Four strength sessions and two easy aerobic sessions per cycle. Recovery can extend the cycle beyond a week.')+`<section class="card">${field('coach-date','Workout date',date,'date',`max="${localDate()}"`)}<p class="fine">Log today, or choose an earlier date to correct your training history.</p><label for="coach-plan">Session · change if you did a different workout</label><select id="coach-plan" ${Object.keys(s.sets).length||s.finished?'disabled':''}>${trainingPlan.map((v,i)=>`<option value="${i}" ${r.plan===i?'selected':''}>${i+1}. ${v.name}</option>`).join('')}</select><p class="fine">The suggested session is preselected. Once sets are logged, its identity stays fixed so your weights keep their meaning.</p><form id="recovery-form"><h2>How do you feel?</h2><div class="grid">${[['energy','Energy',['Good','A little tired','Very low']],['upper','Upper-body soreness',['None / light','Moderate','High']],['lower','Leg soreness',['None / light','Moderate','High']],['core','Core soreness',['None / light','Moderate','High']]].map(([key,label,opts])=>`<div class="field"><label for="recovery-${key}">${label}</label><select id="recovery-${key}" name="${key}">${opts.map((v,i)=>`<option value="${i}" ${(rec[key]||0)===i?'selected':''}>${v}</option>`).join('')}</select></div>`).join('')}</div><label class="check"><input name="pain" type="checkbox" ${rec.pain?'checked':''}><span>Pain or a movement that hurts</span></label><button class="secondary wide">Save recovery & update plan</button></form></section><section class="card workout-hero"><div class="eyebrow">${date} · ${s.finished?'Logged':r.blocked?'Waiting for recovery':'Next in sequence'}</div><h2>${p.name}</h2><p>${r.reason}</p>${p.kind==='strength'?'<p>≈ 60 min · 8 min warm-up + 45 min lifting + 7 min cool-down. Finish earlier if using fewer sets.</p>':''}</section><div class="desktop-grid"><div>${p.kind==='strength'?`<div class="notice"><p>Warm up with easy movement and lighter practice sets. Save only working sets you actually did. Reps in reserve means how many more good reps you could have done.</p>${r.skipCore?'<b>Direct core work is omitted today because of recent training or soreness.</b>':''}${r.light?'<p>Today’s set targets are reduced to two because of your recovery check-in.</p>':''}</div>${p.exercises.map(([id,name,,cue,alt])=>{
 const target=setTarget(r.plan,id,date),sets=s.sets[id]||Array.from({length:target.sets},()=>({})),past=priorExercise(r.plan,id,date)[0],skip=id==='core'&&r.skipCore,locked=r.blocked||skip,visual=exerciseVisual(r.plan,id,name,date).split('<form')[0].replace(/<span class="pill">[^<]*<\/span>/,`<span class="pill">${skip?'Recovery · no planned sets':target.sets+' × '+target.low}${!skip&&target.high!==target.low?'–'+target.high:''}${!skip&&target.timed?' sec':''}${!skip&&target.side?' / side':''}</span>`);
 const source=demoMap[r.plan][id][0],unit=source.includes('Dumbbell')||source==='Goblet_Squat'||source==='Side_Lateral_Raise'?'lb per dumbbell':source.includes('Barbell')||source==='Romanian_Deadlift'?'lb total including bar':id==='core'&&source!=='Pallof_Press'?'added lb; 0 for bodyweight':'lb on machine / added load';
 return `<section class="card exercise">${visual}<p class="fine">${muscleMap[id][0].join(', ')} · supporting: ${muscleMap[id][1].join(', ')||'—'}</p><p>${cue}</p><details><summary>Alternative movement</summary><p>${alt}. Keep this log for the pictured exercise only; loads are not interchangeable.</p></details><div class="notice"><p>${skip?'Leave core work for another day.':loadAdvice(r.plan,id,date)}</p></div>${past?`<p class="fine">Last ${past.date}: ${past.sets.map(v=>`${v.weight??'—'} lb × ${v.reps}${target.timed?' sec':''}`).join(' · ')}</p>`:''}<form data-set-form="${id}"><p class="fine">${unit}. ${target.side?'Enter reps/time for one side after doing both sides.':''} Blank load means unknown; 0 means no external load.</p><div class="set-labels"><span>Set</span><span>lb</span><span>${target.timed?'Seconds':'Reps'}</span><span>In reserve</span><span>Done</span></div>${sets.map((v,i)=>`<div class="set-row"><b>${i+1}</b><input aria-label="${esc(name)} set ${i+1} weight" name="weight-${i}" type="number" min="0" max="1500" step="0.5" inputmode="decimal" value="${v.weight??''}"><input aria-label="${esc(name)} set ${i+1} ${target.timed?'seconds':'reps'}" name="reps-${i}" type="number" min="1" max="600" step="1" inputmode="numeric" value="${v.reps??''}"><input aria-label="${esc(name)} set ${i+1} reps in reserve" name="rir-${i}" type="number" min="0" max="10" step="1" inputmode="numeric" value="${v.rir??''}" ${target.timed?'disabled':''}><input aria-label="${esc(name)} set ${i+1} completed" name="done-${i}" type="checkbox" ${v.done?'checked':''}></div>`).join('')}<button class="secondary wide">Save sets</button><p class="fine">${locked?'Recovery advised: these fields remain available to accurately record or correct work already done.':'Tap Done for each completed set, then Save sets.'}</p></form></section>`
 }).join('')}<button class="primary wide" id="finish-coach">${s.finished?'Update finished session':'Finish session · advance plan'}</button><p class="fine">Finish after saving your sets. If you stopped early, your actual work still counts; uncompleted sets are not invented. Unfinished workouts stay in the queue.</p>`:p.kind==='run'?`<section class="card"><h2>${r.walk?'Make this a walk':'Easy run / walk'}</h2><p>${r.walk?'Your legs worked recently or feel sore. Walk comfortably instead of running today.':'20–30 minutes at conversational effort. New to running? Walk 5 minutes, alternate 1-minute jog/walk six times, then walk 5 minutes.'}</p><form id="coach-aerobic">${field('coach-minutes','Actual minutes, including walking',s.minutes,'number','min="1" max="300" required')}<button class="primary wide" ${r.blocked?'disabled':''}>Save aerobic session & advance</button></form></section>`:`<section class="card"><h2>Rest is part of progress</h2><p>Rest or enjoy comfortable walking and gentle mobility. No missed sessions are stacked onto today.</p><button id="finish-coach" class="primary wide">${s.finished?'Recovery day saved ✓':'Record recovery day'}</button></section>`}${s.finished?'<button class="secondary wide" id="reopen-coach">Reopen session · correct completion</button>':''}</div><div>${muscleHistory(date)}${trainingProfileNote()}<section class="card"><h2>How your plan adapts</h2><p>Upper A → Lower A → easy aerobic → Upper B → Lower B → easy aerobic → recovery. Only a finished session advances the sequence.</p><p>Miss a day? The next session waits. Recent muscle work, soreness, low energy, and your weekly limit can add recovery days. Core work is omitted when recently trained.</p><p>Weights are suggested from the same exercise’s saved sets and effort. Your actual logs are never overwritten with suggested weights.</p><p class="fine">The app uses transparent coaching rules, not a sensor or a medical recovery score. Older check-ins stay saved; unknown workout details are not guessed. Work outside this app is not automatically detected.</p><a href="https://acsm.org/resistance-training-guidelines-update-2026/" target="_blank" rel="noreferrer">ACSM training guidance ↗</a></section>${trainingHistory(date)}</div></div>`;
}
function legacyTrainingHistory(date){return Object.entries(state.days).filter(([dt,d])=>dt<=date&&(d.workout||Object.keys(d.loads||{}).length)).sort(([a],[b])=>b.localeCompare(a)).map(([dt,d])=>`<details><summary>${dt} · Earlier workout record</summary><p>Preserved from the original weekday logger. These entries are not used to guess completed working sets.</p>${Object.entries(d.loads||{}).map(([id,v])=>`<p>${esc(id)}: ${v.weight??'unknown'} lb · ${esc(v.reps)||'reps not recorded'}</p>`).join('')}</details>`).join('')}
function trainingHistory(date){return `<section class="card"><h2>Session history</h2>${sessionsBefore(date,true).reverse().map(([dt,s])=>`<details><summary>${dt} · ${trainingPlan[s.plan].name} · ${s.finished?'Finished':'In progress'}</summary><p>${actualSets(s).length} working sets · ${s.minutes??0} aerobic minutes</p><p>Direct muscles: ${workedMuscles(s).join(', ')||'No direct strength work logged'}</p>${Object.entries(s.sets).map(([id,sets])=>`<p><b>${trainingPlan[s.plan].exercises.find(e=>e[0]===id)[1]}</b><br>${sets.filter(v=>v.done).map(v=>`${v.weight??'unknown'} lb × ${v.reps}${setTarget(s.plan,id,dt).timed?' sec':' reps'}${v.rir!=null?' · '+v.rir+' in reserve':''}`).join('<br>')||'No completed sets'}</p>`).join('')}<button class="secondary" data-coach-edit="${dt}">Edit this session</button></details>`).join('')||'<p class="muted">Your saved sessions will appear here.</p>'}${legacyTrainingHistory(date)}</section>`}
function saveCoach(mutator,message){const date=coachDate||localDate();if(date>localDate())return;const next=structuredClone(state);next.training||={};next.training[date]||={plan:recommendation(date).plan,finished:false,sets:{},recovery:{}};mutator(next.training[date]);try{if(commit(validate(next),message))return true}catch(e){notify('Check the values. Completed sets need reps or seconds; use whole numbers for reps and effort.')}return false}
function bindCoach(){bindDemos();document.querySelectorAll('[data-set-form]').forEach(f=>f.oninput=()=>{f.dataset.dirty='true';f.querySelector('button').textContent='Save sets'});if($('#coach-plan'))$('#coach-plan').onchange=e=>{if(saveCoach(s=>s.plan=Number(e.target.value),'Session selected · recovery rechecked'))render()};if($('#coach-date'))$('#coach-date').onchange=e=>{if(e.target.value&&e.target.value<=localDate()){coachDate=e.target.value;render()}};document.querySelectorAll('[data-coach-edit]').forEach(b=>b.onclick=()=>{go('train');coachDate=b.dataset.coachEdit;render()});if($('#recovery-form'))$('#recovery-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.currentTarget);if(saveCoach(s=>{for(const k of ['energy','upper','lower','core'])s.recovery[k]=Number(data.get(k));s.recovery.pain=data.has('pain')},'Recovery saved · recommendation updated'))render()};document.querySelectorAll('[data-set-form]').forEach(form=>form.onsubmit=e=>{e.preventDefault();const data=new FormData(form),id=form.dataset.setForm,sets=[...form.querySelectorAll('.set-row')].map((_,i)=>{const row={done:data.has('done-'+i)};for(const k of ['weight','reps','rir'])row[k]=data.get(k+'-'+i)==null||data.get(k+'-'+i)===''?null:Number(data.get(k+'-'+i));return row});if(saveCoach(s=>{s.sets[id]=sets;if(!actualSets(s).length)s.finished=false},'Sets saved on this device')){delete form.dataset.dirty;form.querySelector('button').textContent='Saved ✓'}});if($('#finish-coach'))$('#finish-coach').onclick=()=>{if(document.querySelector('[data-set-form][data-dirty]')){notify('Save your edited sets before finishing the session.');return}const date=coachDate||localDate(),s=state.training?.[date],plan=recommendation(date).plan;if(trainingPlan[plan].kind==='strength'&&!actualSets(s||{}).length){notify('Save at least one completed working set first.');return}if(saveCoach(row=>row.finished=true,'Session finished · next workout queued'))render()};if($('#coach-aerobic'))$('#coach-aerobic').onsubmit=e=>{e.preventDefault();if(saveCoach(s=>{s.minutes=Number($('#coach-minutes').value);s.finished=true},'Aerobic session saved'))render()};if($('#reopen-coach'))$('#reopen-coach').onclick=()=>{if(saveCoach(s=>s.finished=false,'Session reopened'))render()};}
